### ISSUE TITLE
mountPath and BasicAuth for Proxy

### ISSUE THREAD

**Issue by itelSchiller** [CarlosOrozco88/ui5-tools#1]
Hi,

Your tool is really cool! It would make the work of some of our developers easier.
But there is still one part missing for efficient work.

For OData BasicAuth and MountPath would be helpful.
Mounthpath is very often needed to simulate a "destionation"
https://www.npmjs.com/package/ui5-middleware-proxy-basicauth
https://www.npmjs.com/package/ui5-middleware-simpleproxy

**Comment by CarlosOrozco88** [comment]
- [ ] Other odataProxy configuration 
- [ ] MountPath configuration
- [ ] ODATA auth

**Comment by CarlosOrozco88** [comment]
I published a new version with mountpath configurable, works with odataProxy "Other" configuration.

You can change it in the workspace configuration or with command ui5-tools.configurator.odataProvider

**Comment by itelSchiller** [comment]
I have tested it with the north wind service, but it does not seem to work.
![image](https://user-images.githubusercontent.com/57350500/83613555-3c0d6b80-a584-11ea-919e-c3ed799a1959.png)
![image](https://user-images.githubusercontent.com/57350500/83613582-462f6a00-a584-11ea-9212-cb319e46644e.png)

**Comment by CarlosOrozco88** [comment]
Hi,

can you try now with version 0.1.8?
Additionally, when Other odataProxy is configured, odataUri and odataMountPath accepts multiple entries:

Configuration:
![image](https://user-images.githubusercontent.com/11719827/83629745-f5773b80-a59a-11ea-8b63-f1e53c8fa8d0.png)

Using first proxy:
![image](https://user-images.githubusercontent.com/11719827/83629713-ea241000-a59a-11ea-842f-4219e1416886.png)

Using second proxy:
![image](https://user-images.githubusercontent.com/11719827/83629692-e1cbd500-a59a-11ea-8eee-b0b5799cc074.png)

You can check it with the example workspace included in this repo.

Thanks for de feedback!

**Comment by itelSchiller** [comment]
Great, now it works! 
That would help a lot of people in the development.

Only in a special case does it get complicated. If mine calls up a server/gateway with a port in the URL https://my.internal.Server:com:8443/

Then the following error appears:
GET http://localhost:3000/mydestination 500 (Internal Server Error)
Error occured while trying to proxy to: localhost:3000

**Comment by CarlosOrozco88** [comment]
I dont know how to check this error, i use this config in work that use ports in the url:
![image](https://user-images.githubusercontent.com/11719827/83763968-a05e2700-a679-11ea-972a-b3c19e5602cd.png)
Your url `https://my.internal.Server:com:8443/` contains two `:`, i dont know if this could be the problem...
That config "is the same" that this one:
![image](https://user-images.githubusercontent.com/11719827/83765097-0ac39700-a67b-11ea-8ccd-aa4b170d999a.png)


By the way, if you think its necessary, i can concatenate the `odataMountPath` with `odataUri` in order to avoid this configuration, so it will look like in the future:
![image](https://user-images.githubusercontent.com/11719827/83765139-1b740d00-a67b-11ea-83aa-ac86b38e34c7.png)

Also i think its necessary another config property to separate `resourcesUri` and `odataUri`, and `Other` option to `resourcesProxy` that allows to customice `resourcesUri`

**Comment by itelSchiller** [comment]
The : behind com was accidental.

Probably that are my own network problems. Because I call it up over VPN.
I can access Gateway's OData service directly from the browser, but not the proxy.

**Comment by CarlosOrozco88** [comment]
Im calling it up over VPN too.
I think i will activate logLevel of this proxy to debug and other proxys to error debugLevel (next version), then in vscode menu: Help > Toggle Developer Tools > Console so you can check the logs, i hope we can find some helpfull messages...

By the way, you can check it now but all proxy are in info debugLevel.

**Comment by CarlosOrozco88** [comment]
Now you can create a .env file in root workspace with:
UI5TOOLS_ODATA_USER=user1
UI5TOOLS_ODATA_PASSWORD=pass1
If you have multiple destinations, then the next ones:
UI5TOOLS_ODATA_USER_2=user2
UI5TOOLS_ODATA_PASSWORD_2=pass2
UI5TOOLS_ODATA_USER_3=user3
UI5TOOLS_ODATA_PASSWORD_3=pass3
...
Can you have a look, please?

Thanks!

**Comment by itelSchiller** [comment]
that works with authentication. also with the mutiple mountpath/destionation
My own mistake is that the gateway has a self-signed certificate. Either you would have to install the certificate on your device, or you could disable this SSL check, like in Postman or in the ui5-tooling-middleware (see screenshots)
<img width="349" alt="Bildschirmfoto 2020-06-09 um 08 40 21" src="https://user-images.githubusercontent.com/57350500/84115875-158d7b80-aa2f-11ea-9a4d-d79f3a8d1baa.png">
![image](https://user-images.githubusercontent.com/57350500/84115951-3524a400-aa2f-11ea-92ed-ede50d595c92.png)

**Comment by CarlosOrozco88** [comment]
Hi!

In 0.3.1 ssl check is disabled by default. I hope this solves the problem...
