### ISSUE TITLE
Server: redirect to SAP system with different clients

### ISSUE THREAD

**Issue by SuKGunni3** [CarlosOrozco88/ui5-tools#14]
is it possible to supply any url parameters for the first connection to the proxy odata URI?
im trying to connect to a second client of a sap system but i don't know if/how it is possible to change the Client ID

**Comment by CarlosOrozco88** [comment]
By the way, if it is possible, you can do the trick adding metadataUrlParams to the oDataModel:
![image](https://user-images.githubusercontent.com/11719827/136536517-585ef62c-ecef-4854-86b8-b26977c6313e.png)

also in manifest file:
![image](https://user-images.githubusercontent.com/11719827/136536391-548f3531-d24b-4df6-8d14-399e1abf0146.png)
