### ISSUE TITLE
Multiple destinations

### ISSUE THREAD

**Issue by MLDOliveira** [CarlosOrozco88/ui5-tools#2]
Hi Carlos I just found out about your project and I would like to know if there is a way that I can have multiple oData services (destinations) to proxy.

For example, I can connect to S/4 HANA using 1 destination and connect to C4C using another destination?

**Comment by CarlosOrozco88** [comment]
Hi.

Yes, you can configure n diferent odataProxies with ```odataProxy:"Other"```, then in `odataUri` you can list n diferent urls separated with comma, ```odataUri:"https://gateway.com:8080/sap/,https://northwind.com/``` and ```odataMountPath:"/sap,/path2"```
 
With command ui5-tools > Configurator > odata you can configure this.

I hope it will help you.

**Comment by MLDOliveira** [comment]
Thanks @CarlosOrozco88 for the quick answer.

And about the authentication part for each destination?

**Comment by CarlosOrozco88** [comment]
Currently, i am working to support .env file with n users/passwords to handle authentication. 

Probably, the next version will include it. Also i think i will include one breaking change with resourcesUri (using gateway) separated from odataUri (currently uses the same property odataUri).

**Comment by CarlosOrozco88** [comment]
#1 
Can you check this issue, there i am discussing auth with multiple destinations.

Thanks

**Comment by CarlosOrozco88** [comment]
Conversation continues in #1
