### ISSUE TITLE
Publish to Open VSX

### ISSUE THREAD

**Issue by zendynar** [CarlosOrozco88/ui5-tools#20]
Since this repo is already open source, it would be nice if this extension could be also published to [Open VSX](https://open-vsx.org/). Here's the [procedure](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).
This would benefit other IDEs such as SAP BAS or Gitpod since they're based on Eclipse Theia which can handle extensions (officially) only from the Open VSX registry and also an open source build of VSCode called [VSCodium](https://github.com/VSCodium/vscodium).

**Comment by CarlosOrozco88** [comment]
Thanks for the suggestion!

The extension is now published:
https://open-vsx.org/extension/carlosorozcojimenez/ui5-tools

Btw, I have not tested it outside vscode itself.
