### ISSUE TITLE
ui5-tools.srcFolder - not webapp

### ISSUE THREAD

**Issue by sammok83** [CarlosOrozco88/ui5-tools#5]
Hi there,

Thanks for the extension. I have some old ui5 apps that i need to tweak (without the webapp folder). File structure as follows:
![older](https://user-images.githubusercontent.com/10509241/95654212-4d760e00-0b4a-11eb-8d6a-e6264df93726.jpg)

For newer ui5 apps with the webpp folder, that works fine. However for the older style apps, the extension doesn't detect it even after setting the ui5-tools.srcFolder to "".

Is there a way around this?

**Comment by CarlosOrozco88** [comment]
Hi!

I will try to fix it as soon as I can.

Thanks!

**Comment by CarlosOrozco88** [comment]
Hi, can you try now? Now it is possible to configure srcFolder and distFolder with empty value.
