### ISSUE TITLE
Set UI5 version

### ISSUE THREAD

**Issue by AnOffe** [CarlosOrozco88/ui5-tools#6]
Hello,
this is a great extension and it works very well.
One question:
When starting the server and pressing "info" at the start-screen, i get a UI5 version number of 1.60.13.
This is the version, i set in the extension settings in vscode, all fine.
But when i press "Launchpad" and start my application from there, then pressing ctrl+alt+shift+p it shows
a version 1.52.20.
How can i change that?

Regards,

Andre

**Comment by CarlosOrozco88** [comment]
Hi,
it depends on resourcesProxy. If you are proxing "Gateway", the extension will use its version.
If you configure "i5-tools.server.resourcesProxy" = "CDN SAPUI5", it should use the "ui5-tools.ui5Version" configured instead.
Can you check this?

Thanks!

**Comment by AnOffe** [comment]
Hi Carlos,
yes, i use "Gateway" and pointing to the SAP-Server, but on my  
SAP-System there is also not the displayed version.
I changed the Server during development, maybe the old ui5 version is cached?
If so, can i clear this?

Thanks,

Andre


Zitat von Carlos <notifications@github.com>:

**Comment by AnOffe** [comment]
Hi,

changing to CDN SAPUI5 does not change anything. 
Changing the UI5 Version results in 

`Uncaught ReferenceError: ui is not defined
    at eval (eval at jQuery.sap.globalEval (jquery.sap.global-dbg.js:5713), <anonymous>:1:12)
    at Object.jQuery.sap.globalEval (jquery.sap.global-dbg.js:5713)
    at constructor.u._executeOnInit (Core-dbg.js:1117)
    at constructor.u.init (Core-dbg.js:1071)
    at Core-dbg.js:347
    at l (jquery.sap.global-dbg.js:2662)
    at S.finishTask (jquery.sap.global-dbg.js:2657)
    at HTMLDocument.<anonymous> (Core-dbg.js:355)
    at p (jquery-dbg.js:3187)
    at Object.fireWith [as resolveWith] (jquery-dbg.js:3317)` 

Do you have an example-configuration for using the UI5 version from the SAP-Gateway-Server? It is in my local network reachable per IP-Adress.

**Comment by CarlosOrozco88** [comment]
Hi,

it seems that your gateway version is, for example, 1.52, and the configuration file is pointing to another version, like 1.70.

Internally, the extension builds the main page and launchpad with the correct bootstrap code of the configuration property, but if the gateway has another version it will not run.

Check if the gw version its in sync with the extension version.

You can check the projects also, localhost:3000/{FODERNAME}

**Comment by AnOffe** [comment]
Hi,

now I use "Gateway" and left UI5Version empty. 
That works and the ui5 version is the correct version from my server.

Many thanks!

One last question, what do you mean with {FODERNAME} ?

**Comment by CarlosOrozco88** [comment]
It was a mistake, i mean FOLDERNAME.
Thanks!
